### ISSUE TITLE
Incompatible configuration with Sysmon 13.21

### ISSUE THREAD

**Issue by sebastiendamaye** [olafhartong/sysmon-modular#100]
`Incorrect field ParentImage` and `Incorrect field TargetImage` errors appear during installation with Sysmon 13.21:

```
C:\Users\Public\Downloads\sysmon>Sysmon64.exe -i sysmonconfig.xml


System Monitor v13.21 - System activity monitor
Copyright (C) 2014-2021 Mark Russinovich and Thomas Garnier
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.
Sysinternals - www.sysinternals.com

Loading configuration file with schema version 4.60
Sysmon schema version: 4.70
Incorrect field ParentImage
Incorrect field TargetImage
Configuration file validated.
Sysmon64 installed.
SysmonDrv installed.
Starting SysmonDrv.
SysmonDrv started.
Starting Sysmon64..
Sysmon64 started.

```

**Comment by Gerh-Hack** [comment]
I have the same problem.
I even tried to search for old versions of Sysmon and I can't find any link to it.

**Comment by sebastiendamaye** [comment]
@Gerh-Hack Thx for confirming the issue! You can find previous versions of sysmon using WayBack machine (archive.org). For example, to download sysmon 13.10, you can use this link: https://web.archive.org/web/20210428134528/https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon.

**Comment by olafhartong** [comment]
Apologies, this was due to two bad commits on my end, they have been fixed now.
