### ISSUE TITLE
error with merging script line 137/char13

### ISSUE THREAD

**Issue by janlinhart-BC** [olafhartong/sysmon-modular#106]
Hello, I experience some error running the merging script:

1. Running ps script has some faults on the output:

**PS C:\GITHUB\sysmon-modular-master>** Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig-test.xml

-----------------------------------------------------------------------
![Screenshot 2021-07-07 134623](https://user-images.githubusercontent.com/80322596/124754228-438f0900-df2a-11eb-82af-62717e5444ba.png)
![Screenshot 2021-07-07 134707](https://user-images.githubusercontent.com/80322596/124754231-44279f80-df2a-11eb-8ad5-a19abc97495e.png)

**Comment by olafhartong** [comment]
should be fixed with all recent improvements
