### ISSUE TITLE
Error When Running Merge-SysmonCMLConfiguration

### ISSUE THREAD

**Issue by Th3J0kr** [olafhartong/sysmon-modular#11]
When running the Merge-SysmonCMLConfiguration from a fresh pull of PSSysmonTools and sysmon-modular it throws the error : 

`Test-SysmonConfiguration : The 'onmatch' attribute is invalid - The value 'Exclude' is invalid according to its datatype 'urn:schemas-specterops.io:SysmonConfiguration:IncludeExcludeType' - The
Enumeration constraint failed.
At C:\Users\c11900\Documents\Engineering\sysmon\SysmonTools\PSSysmonTools\PSSysmonTools\Code\ConfigurationMerger.ps1:75 char:44
+ ... ionResult = Test-SysmonConfiguration -Path $ReferencePolicyFullPath - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-SysmonConfiguration`

Not sure if it matters since I wasn't able to compile a config to run but this on Schema v 4.1 and sysmon v 8.0.0.

**Comment by olafhartong** [comment]
Thanks for mentioning it. I'll have a look at this

**Comment by admiralbenbou** [comment]
I got the same, sysmon 8.0/8.2,8.4 with different configs. All configurations are valid (sysmon works with it), but "test-sysmonconfiguration" fails on files with custom names in XML (for ex. <Image condition="image" name="THATS WHY IT FAILS">pcalua.exe</Image> in olaf.xml.txt) with message The 'name' attribute is invalid. At the same time config SoS and another, that dont have custom attributes, passes this tests ok. And after removing this attributes(olaf.xml.nocustom.txt) with regex, test passes.



[olaf.xml.nocustom.txt](https://github.com/olafhartong/sysmon-modular/files/2811317/olaf.xml.nocustom.txt)
[olaf.xml.txt](https://github.com/olafhartong/sysmon-modular/files/2811250/olaf.xml.txt)
[SoS.xml.txt](https://github.com/olafhartong/sysmon-modular/files/2811251/SoS.xml.txt)
