### ISSUE TITLE
"Trusted Script Proxy Exectuion" or "Trusted Script Proxy Execution"

### ISSUE THREAD

**Issue by Yuvraj-Takey** [olafhartong/sysmon-modular#112]
Hello,
I was exploring Sysmon Config file (Location: "master/sysmonconfig.xml") and under section Event ID 1, I got two MITRE Techniques with the same name. In both names last word is different **("Exectuion" <------> "Execution")**.

I am not sure whether it is right or wrong, just need to verify with the team member.

Thank you

**Comment by torstenbeer** [comment]
This looks like a typo [T1216](https://attack.mitre.org/techniques/T1216/).

**Comment by olafhartong** [comment]
yes, great find, thanks! resolving now
