### ISSUE TITLE
FileDelete vs. FileDeleteDetected inconsistent

### ISSUE THREAD

**Issue by maederm** [olafhartong/sysmon-modular#117]
Hi

Is there a reason for the rules inside of [23_file_delete](https://github.com/olafhartong/sysmon-modular/tree/master/23_file_delete) to be different from [26_file_delete_detected](https://github.com/olafhartong/sysmon-modular/tree/master/26_file_delete_deteted) (excluding the tag)?

Best Regards,
maederm

**Comment by faressalhi** [comment]
Hello, 

TLDR, 
FileDeleteDetected (event ID 26) : a file was deleted.

FileDelete (event ID 23) : a file was deleted + sysmon will archive a copy of this file and save it to the archive directory (C:\Sysmon by default).

More details on those events : https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon 

Cheers

**Comment by maederm** [comment]
I know about the different behaviors of both rule types. My train of thought was that in some environments you may want to detect the deletion and in others you want to detect and archive.
Thinking about it now the existing policies are probably opinionated use cases.
