### ISSUE TITLE
New exclusions for antimalwares - ProcessCreate

### ISSUE THREAD

**Issue by d4ph1l** [olafhartong/sysmon-modular#12]
Hi,

Congrats for this great work!
just suggesting a few more exlclusions :)

**TREND MICRO AV:**
`
<Sysmon schemaversion="3.4">
 <ProcessCreate onmatch="exclude">
<Image condition="is">C:\Program Files (x86)\Trend Micro\BM\TMBMSRV.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Trend Micro\OfficeScan Client\TmopExtIns32.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Trend Micro\OfficeScan Client\TmExtIns.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Trend Micro\OfficeScan Client\TmListen.exe</Image>
</ProcessCreate>
`

**SOPHOS AV:**
`
<Sysmon schemaversion="3.4">
 <ProcessCreate onmatch="exclude">
Image condition="is">C:\Program Files (x86)\Sophos\Sophos Anti-Virus\Web Intelligence\swi_service.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Sophos Anti-Virus\Web Control\swc_service.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Sophos System Protection\ssp.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Remote Management System\RouterNT.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\AutoUpdate\ALsvc.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Sophos Anti-Virus\SAVAdminService.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Remote Management System\ManagementAgentNT.exe</Image>
</ProcessCreate>
`

**ESET NOD32 AV:**
`
<Sysmon schemaversion="3.4">
 <ProcessCreate onmatch="exclude">
<Image condition="is">C:\Program Files\ESET\ESET Nod32 Antivirus\ekrn.exe</Image>
    </ProcessCreate>
`

**MALWAREBYTES ANTIMALWARE:**
`
<Sysmon schemaversion="3.4">
    <ProcessCreate onmatch="exclude">
    <Image condition="is">C:\Program Files\Malwarebytes\Anti-Malware\mbam.exe</Image>
    <Image condition="is">C:\Program Files\Malwarebytes\Anti-Malware\mbamservice.exe</Image>
    <Image condition="is">C:\Program Files\Malwarebytes\Anti-Malware\mbamtray.exe</Image>
    </ProcessCreate>
`

**KASPERSKY AV:**
`
<Sysmon schemaversion="3.4">
 <ProcessCreate onmatch="exclude">
<Image condition="begin with">C:\Program Files\Kaspersly Lab\</Image>
    </ProcessCreate>
`

**WINDOWS DEFENDER (Win 8+):**
`
<Sysmon schemaversion="3.4">
 <ProcessCreate onmatch="exclude">
<Image condition="contains">C:\ProgramData\Microsoft\Windows Defender\Platform\</Image>
    </ProcessCreate>
`

NB: Kaspersky and Windows Defender leverage non-consistent paths (depending on antimalware/engine version), so that I believe the only solution is to use the "contains" operand, even if less efficient on the perfs side. 

My 2 cents,

--
Phil

**Comment by olafhartong** [comment]
Thanks for submitting Phil, this is great! 
The risk in whitelisting Kaspersky and  Win Defender that way is to open a larger attack vector, I'm not sure if I'll add those. The rest is very useful, appreciate it a lot.
