### ISSUE TITLE
Include file format: merge full directories

### ISSUE THREAD

**Issue by hkelley** [olafhartong/sysmon-modular#120]
While we do our first rounds of tuning, I want to incorporate all of your rules for a small set of event IDs.   At first, I tried doing this by creating an include file that contained folder (not rule) names, e.g.:
```
7_image_load
17_18_pipe_event
```

I then realized that `Merge-AllSysmonXml  -IncludeList` expects XML file names.   

Is there already a way to accomplish what I describe above?  If not,  may I suggest adding the *elseif* block shown below?

```
                if($Inclusion -like '*.xml'){
                    if(Test-Path -Path $Inclusion){
                        $InclusionFullPaths += $Inclusion
                    }
                    else{
                        Write-Error "Referenced Rule Inclusion Not Found: $Inclusion"
                    }
                }
                elseif((Test-Path $Inclusion) -and ($InclusionFolder = Get-ChildItem -Path $BasePath -Directory -Name $Inclusion ))
                {
                    foreach($Inclusion in Get-ChildItem -Path $InclusionFolder -File -Filter "*.xml")
                    {
                        $InclusionFullPaths += $Inclusion.FullName
                    }
                }
```

Happy to do a PR if this is useful.

**Comment by olafhartong** [comment]
Oh no, currently there is no support for complete directories, only on file level. A PR would be cool, that way you're getting the proper credits for that code.
