### ISSUE TITLE
New exclusions for antimalwares - NetworkConnect

### ISSUE THREAD

**Issue by d4ph1l** [olafhartong/sysmon-modular#13]
Hi again,

same thing, for network trafic belonging to antimalwares solutions: connection to management server, cloud based services, etc. Quite noisy.

**TRENDMICRO AV:**
`<NetworkConnect onmatch="exclude">
<Image condition="is">C:\Program files (x86)\Trend Micro\OfficeScan Client\tmlisten.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Trend Micro\BM\TMBMSRV.exe</Image>
 </NetworkConnect>`

**SOPHOS ANTIVIRUS:**
` <NetworkConnect onmatch="exclude">
<Image condition="is">C:\Program Files (x86)\Sophos\Sophos Anti-Virus\Web Intelligence\swi_service.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\AutoUpdate\ALsvc.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Remote Management System\RouterNT.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Sophos Anti-Virus\Web Control\swc_service.exe</Image>
      <Image condition="is">C:\Program Files (x86)\Sophos\Sophos Anti-Virus\Web Intelligence\swi_service.exe</Image>
      <Image condition="is">C:\Program Files\Sophos\Sophos Network Threat Protection\bin\SntpService.exe</Image>
 </NetworkConnect>`

**ESET NOD32 AV:**
` <NetworkConnect onmatch="exclude">
<Image condition="is">C:\Program Files\ESET\ESET Nod32 Antivirus\ekrn.exe</Image>
 </NetworkConnect>
`

HTH.

--
Phil

**Comment by olafhartong** [comment]
again, great stuff! Will create modules for this, thanks!
