### ISSUE TITLE
HKCU - Additional Files

### ISSUE THREAD

**Issue by kevinelwell** [olafhartong/sysmon-modular#132]
well, I believe you're completely right. This is an oversight on my end :P thanks for bringing it to my attention!! I'll change them straight away.

_Originally posted by @olafhartong in https://github.com/olafhartong/sysmon-modular/issues/130#issuecomment-1127941424_

There are several additional .XML files that reference HKCU:

include_internet_explorer_extentions_helpers_or_toolbars.xml
include_environment_mod.xml
include_autoruns_and_startup_keys.xml
include_com_hijack.xml
include_windows_store_tampering.xml
include_office.xml
include_windows_port_changes.xml
include_windows_integrity_monitoring.xml
include_windows_disabling_security_services.xml
sysmonconfig.xml 

Cheers!

**Comment by kevinelwell** [comment]
bump

**Comment by olafhartong** [comment]
thanks for pointing them out, I've fixed them all now

**Comment by kevinelwell** [comment]
You're most welcome! Thank you for sharing this fantastic resource with the community!
