### ISSUE TITLE
Excluding __PSScriptPolicyTest_ files

### ISSUE THREAD

**Issue by m3hdx** [olafhartong/sysmon-modular#137]
I'm seeing a good number of logs related to PowerShell files that start with "__PSScriptPolicyTest_". Based on my little research, these files are being executed by MS PowerShell to test against the Applocker. 

I wonder if anyone else has seen these in their environment and wrote an exclusion for it.

Any help and insight on this would be greatly appreciated.

Thanks,
Mehdi
[T1193_redacted.csv](https://github.com/olafhartong/sysmon-modular/files/8904225/T1193_redacted.csv)

**Comment by olafhartong** [comment]
added as an exclusion, thanks

**Comment by krandill** [comment]
hi @olafhartong I seem to have the same problem right now, even though my rule exist in my sysmon_config.xml:
       Rule groupRelation="and">
          Image condition="is">C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe</Image
          TargetFilename condition="contains all">C:\Windows\Temp;__PSScriptPolicyTest;.ps1</TargetFilename
          User condition="is">NT AUTHORITY\SYSTEM</User
        </Rule

(removed some of the < and > so the text is not masked by github but they are present on my actual sysmonconfig.xml)

i got this alert from most of my endpoints.:


    "data": {
      "win": {
        "eventdata": {
          "image": "C:\\\\WINDOWS\\\\system32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe",
          "processGuid": "{1334d01c-e6dd-6915-c575-000000002700}",
          "processId": "22296",
          "utcTime": "2025-11-13 14:10:38.243",
          "targetFilename": "C:\\\\Windows\\\\SystemTemp\\\\__PSScriptPolicyTest_t0nmy2r5.zsj.ps1",
          "ruleName": "technique_id=T1059.001,technique_name=PowerShell",
          "creationUtcTime": "2025-11-13 14:10:38.242",
          "user": "NT AUTHORITY\\\\SYSTEM"

any tips on what i may have done wrong?

**Comment by krandill** [comment]
from what i gather,

the existing rule is:

`<Sysmon schemaversion="4.30">
   <EventFiltering>
      <RuleGroup name="" groupRelation="or">
         <FileCreate onmatch="exclude">
            <Rule groupRelation="and">
               <Image condition="is">C:\Windows\system32\wsmprovhost.exe</Image> 
               <TargetFilename condition="contains all">C:\Users\;\AppData\Local\Temp;__PSScriptPolicyTest;.ps1</TargetFilename>
            </Rule>
            <Rule groupRelation="and">
               <Image condition="is">C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe</Image> 
               <TargetFilename condition="contains all">C:\Windows\Temp;__PSScriptPolicyTest;.ps1</TargetFilename>
               <User condition="is">NT AUTHORITY\SYSTEM</User>
            </Rule>
         </FileCreate>
      </RuleGroup>
   </EventFiltering>
</Sysmon>`

but my targetFilename C:\Windows\SystemTemp instead of C:\Windows\Temp. which make the rule not effective.

Also, i dont know if it could be interesting or if you would like to add this, but some of our systems are installed in french and  <User condition="is">NT AUTHORITY\SYSTEM</User> would not work since the user is in french (AUTORITE NT\\Système) instead of NT AUTHORITY\SYSTEM

how does sysmon handle different languages for users? is it possible to have the rules work for both language?
