### ISSUE TITLE
Rule Group Relation in Network Connect / include_relaying.xml

### ISSUE THREAD

**Issue by ErichSutter** [olafhartong/sysmon-modular#142]
Hello all

Should the RuleGroup relation in https://github.com/olafhartong/sysmon-modular/tree/master/3_network_connection_initiated/include_relaying.xml not be "and"? It is currently set to "or", and either the first or the second conditon (rule) will always be true, so the RuleGroup will always evaluate to true and possibly generate lots of logs. 

Cheers, Erich

**Comment by ErichSutter** [comment]
The conditions could probably be packed into one rule:

```
<Sysmon schemaversion="4.30">
	<EventFiltering>
		<RuleGroup name="" groupRelation="or">
			<NetworkConnect onmatch="include">
				<Rule groupRelation="and">
					<SourcePort name="technique_id=T1557,technique_name=Adversary-in-the-Middle" condition="is any">445;389;8492;636;3268;3269</SourcePort>
					<Image condition="is not">C:\Windows\System32\lsass.exe</Image>
        				<Image condition="is not">c:\Windows\System32\dsamain.exe</Image>
        				<ProcessId condition="is not">4</ProcessId>
        			</Rule>
			</NetworkConnect>
		</RuleGroup>
	</EventFiltering>
</Sysmon>
```

**Comment by olafhartong** [comment]
good suggestion, adding it
