### ISSUE TITLE
condition="is" is removed after merge. 

### ISSUE THREAD

**Issue by 82d28a** [olafhartong/sysmon-modular#15]
When Generate-Sysmon-config.ps1 is run and has a condition="is" the condition is stripped from the filter row. Please clarify if this is intended. 

Before merge:

`<Image condition="is">C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeC2RClient.exe</Image> <!-- Microsoft:Office Click2Run-->`

After merge:
`<Image>C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeC2RClient.exe</Image>`

**Comment by olafhartong** [comment]
This is correct, both are fine the merged is an optimal version, less verbose
