### ISSUE TITLE
Include Top Level Groups not working?

### ISSUE THREAD

**Issue by defensivedepth** [olafhartong/sysmon-modular#156]
According to the docs, we should be able to include the entire top level groups in include/exclude lists, like this:

![image](https://user-images.githubusercontent.com/954732/204842359-256e93f5-9735-45c3-b33d-03a0795bb101.png)

When I do this, I get the following error:

![image](https://user-images.githubusercontent.com/954732/204842446-5a32950a-e421-4009-ad91-a3cfa2cfe907.png)

**Comment by olafhartong** [comment]
When you set the base path you should only use the subdir/filename to the IncludeList, in your case just 0_custom_configuration\local_tuning.... etc that should work

**Comment by defensivedepth** [comment]
Still no go:

![image](https://user-images.githubusercontent.com/954732/205159150-55b5bfd9-f054-4d97-93c9-19976af3a35c.png)
