### ISSUE TITLE
Credential Dumping - false positive?

### ISSUE THREAD

**Issue by griffo138** [olafhartong/sysmon-modular#16]
I'm getting the following created in the event log. 

`The description for Event ID 10 from source Microsoft-Windows-Sysmon cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

technique_id=T1003,technique_name=Credential Dumping
2019-01-03 16:01:06.470
EV_RenderedValue_2.00
820
8872
C:\Windows\system32\svchost.exe
EV_RenderedValue_6.00
740
C:\Windows\system32\lsass.exe
5120
C:\Windows\SYSTEM32\ntdll.dll+a5fc4|C:\Windows\System32\KERNELBASE.dll+5d8e4|c:\windows\system32\lsm.dll+f6fb|C:\Windows\System32\RPCRT4.dll+784a3|C:\Windows\System32\RPCRT4.dll+dbc6d|C:\Windows\System32\RPCRT4.dll+a8dc|C:\Windows\System32\RPCRT4.dll+5a214|C:\Windows\System32\RPCRT4.dll+5912d|C:\Windows\System32\RPCRT4.dll+599db|C:\Windows\System32\RPCRT4.dll+39b5c|C:\Windows\System32\RPCRT4.dll+39fdc|C:\Windows\System32\RPCRT4.dll+542ec|C:\Windows\System32\RPCRT4.dll+55b4b|C:\Windows\System32\RPCRT4.dll+4864a|C:\Windows\SYSTEM32\ntdll.dll+2864e|C:\Windows\SYSTEM32\ntdll.dll+29fb9|C:\Windows\System32\KERNEL32.DLL+8364|C:\Windows\SYSTEM32\ntdll.dll+6e851
`

We've had sysmon 7 running on this machine for several months but I don't think it's had ProcessAccess logging enabled, so I've not seen this before.

**Comment by olafhartong** [comment]
This is enabled to detect malicious processes from accessing the lsass memory. There will be quite some legitimate processes doing so as well. 
If you find this too noisy I suggest adding some additional exclusion rules or removing the include of this rule.
