### ISSUE TITLE
Sysmon 9.0

### ISSUE THREAD

**Issue by momilor** [olafhartong/sysmon-modular#17]
Hi Olaf and thanks for the great work!
Will the sysmon-modular work also for sysmon 9.0?

Cheers,

momilor

**Comment by olafhartong** [comment]
Yes and no ;) the generated content does not yet make use of the rule grouping.

I've just added a manually generated version of a v9 config and will maintain this till I've rebuilt the PSSysmonTools to support the 4.2 schema. This will be quite a pain so it might take a while

**Comment by momilor** [comment]
Thanks a lot Olaf!
