### ISSUE TITLE
i can't generate new configuration 

### ISSUE THREAD

**Issue by mohamedmarrouchi** [olafhartong/sysmon-modular#18]
Test-SysmonConfiguration : Schema version 4.2 is not supported.
Au caractère C:\PSSysmonTools\PSSysmonTools\Code\ConfigurationMerger.ps1:128 : 33
+ ... ionResult = Test-SysmonConfiguration -Path $PolicyFullPath -ErrorActi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-SysmonConfiguration

**Comment by olafhartong** [comment]
Remove the sysmonconfig-v9.xml then it will work. I’ll think of a better way to distribute that one.
