### ISSUE TITLE
Error whle running Generate-sysmon-config.ps1

### ISSUE THREAD

**Issue by Sumitsrjhs** [olafhartong/sysmon-modular#20]
Hi

While running the script after executing "Import-Module .\PSSysmonTools.psm1 ", its throwing error 

The term 'Merge-SysmonXMLConfiguration' is not recognized as the name of a cmdl
et, function, script file, or operable program. Check the spelling of the name,
 or if a path was included, verify that the path is correct and try again.
At H:\HELK\sysmon-modular\Generate-Sysmon-config.ps1:28 char:188
+ Get-ChildItem -Path . -Filter *.xml -Recurse -ErrorAction SilentlyContinue |
Where {$_.Name -NotMatch "sysmonconfig(?:-\d{2}-\w{3}-\d{4}-\d{2}-\d{2})?.xml"}
 | Merge-SysmonXMLConfiguration <<<<  -ReferencePolicyPath .\baseconfig.xml -Ex
cludeMergeComments | Out-File sysmonconfig.xml -Encoding UTF8
    + CategoryInfo          : ObjectNotFound: (Merge-SysmonXMLConfiguration:St
   ring) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Please suggest

**Comment by olafhartong** [comment]
It seems like you have not imported the PSSysmon module > 
https://github.com/olafhartong/sysmon-modular#required-actions

Can you retry that?

**Comment by Sumitsrjhs** [comment]
Hi

Thanks a lot for your response. I am doing process step by step as stated in wiki, so I already executed import-module process.

Please suggest.

**Comment by olafhartong** [comment]
The script has been replaced, should not be an issue anymore

**Comment by joker2013** [comment]
You need to rename Merge-SysmonXml.ps1 -> Merge-SysmonXml.psm1
and execute Import-Module Merge-SysmonXml.psm1

**Comment by joker2013** [comment]
![image](https://user-images.githubusercontent.com/5401399/66372187-15c00d80-e9ae-11e9-8419-4f626a3c9d7d.png)

**Comment by joker2013** [comment]
![image](https://user-images.githubusercontent.com/5401399/66372338-6afc1f00-e9ae-11e9-8979-72be35fd2b5c.png)
![Uploading image.png…]()
