### ISSUE TITLE
Config file not working as expected

### ISSUE THREAD

**Issue by PurpleV0id** [olafhartong/sysmon-modular#28]
Hi,

I have been testing the latest master branch with the latest sysmon, I have customised by removing some of the rules for tools i do not use, i have also added a new rule as below.  From my testing though it seems part of the config is not applying,  My rule is not applied and generates alot of events, if i dump the config with sysmon -c , picking some key executables from the config i cannot find them in the dump, where as if i use swiftonsecuritys z-alpha config i can find matching words.

Below is my 10_process_access config and an example of portion of the event firing still.  Also event 12 seems to hit alot whereas z-alpha doesnt, comparing the configs i cannot see why it would be triggering unless the event hides the actual reg path.  I have tried your default config and seem to have similar events triggering with the obvious inclusion of sfc.exe.

Any suggestions/tests?

<Sysmon schemaversion="4.22">
   <EventFiltering>
 <RuleGroup name="" groupRelation="or">
    <ProcessAccess onmatch="exclude">
  	<SourceImage condition="end with">sfc.exe</SourceImage>
      </ProcessAccess>  
</RuleGroup>
</EventFiltering>
</Sysmon>

Process accessed:
RuleName: 
UtcTime: 2019-10-30 07:47:08.072
SourceProcessGUID: {d1bab7ef-51e6-5dad-0000-001046290400}
SourceProcessId: 4336
SourceThreadId: 9040
SourceImage: C:\Program Files\Cisco\AMP\6.3.7\sfc.exe

Registry object added or deleted:
RuleName: 
EventType: CreateKey
UtcTime: 2019-10-30 07:51:16.454
ProcessGuid: {d1bab7ef-51e5-5dad-0000-001017940300}
ProcessId: 2408
Image: C:\WINDOWS\system32\svchost.exe
TargetObject: HKCR

Thanks

**Comment by olafhartong** [comment]
Hi, assuming you're on Sysmon 10.42 now you can do this for Cisco AMP

<Sysmon schemaversion="4.22">
   <EventFiltering>
 <RuleGroup name="" groupRelation="or">
      <ProcessAccess onmatch="exclude">
		<SourceImage condition="contains all">C:\Program Files\Cisco\AMP\;sfc.exe</SourceImage>
      </ProcessAccess>
</RuleGroup>
</EventFiltering>
</Sysmon>


For the second one I would need a bit more information :D

**Comment by PurpleV0id** [comment]
Hi,

Sorry I forgot to update, I managed to dedicate some time to it again last week. It started working just fine oddly enough, although my colleague had some issues with applying a new template. I believe it was more sysmon related not updating from the template despite uninstalling and reinstall.

My colleague found sysmon -c seemed to get it to refresh the template after his instance of sysmon acting strangely when installing with a template.

Thanks
Phil

Sent from ProtonMail mobile

-------- Original Message --------
