### ISSUE TITLE
Feature Request: Automated removal of entries

### ISSUE THREAD

**Issue by Rivosyke** [olafhartong/sysmon-modular#29]
Fantastic work on doing the mapping; love it! 

We use a modified version of either yours or Swift's config and remove entries from certain areas to reflect what we want to see in our environment. With modular, it'd be super handy if we could have a file of things we want to remove that the script would reference when it's done putting things together that would then remove those entries. 

That way, we could update from the git when there's a change and not have to manually go remove entries from the final product.

Thanks!

**Comment by olafhartong** [comment]
Hi thanks for the feedback, happy to see you're finding it useful!

I really like your idea, I'll add it to my todo list.

**Comment by olafhartong** [comment]
this is now part of the merge script
