### ISSUE TITLE
I don't have the  Merge-AllSysmonXml in my directory.

### ISSUE THREAD

**Issue by Hilmand** [olafhartong/sysmon-modular#34]
When I try to paste the command      _Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml_      in Powershell in give me the following error.      

Merge-AllSysmonXml : The term 'Merge-AllSysmonXml' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString |  ...
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Merge-AllSysmonXml:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

And Secondly: I don't have Merge-AllSysmonXml in my directory

**Comment by koppensb** [comment]
Hi,

you have to load the ps via 

.  .\Merge-SysmonXml.ps1
then you can use the Merge-AllSysmonXml

**Comment by koppensb** [comment]
Generating a config
PowerShell
git clone https://github.com/olafhartong/sysmon-modular.git
cd sysmon modular
. .\Merge-SysmonXml.ps1
Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml

**Comment by Hilmand** [comment]
I have already done that. 
When I go for the second command it gives me the error

**Comment by koppensb** [comment]
Do you get any message from the first command or just a new line?

**Comment by Hilmand** [comment]
It worked.. thank you .. earlier I was doing the first step with single
dot....


BTW in which directory I have to be to run this command sysmon.exe
-accepteula -i sysmonconfig.xml

sysmon-modular or sysmon ??

**Comment by koppensb** [comment]
This command is for installing the sysmon executable downloaded from Microsoft and is not directly connected to the config file generation.

**Comment by Hilmand** [comment]
Alright.. It's all resolved now. Thank you for your time Sir.

**Comment by Hilmand** [comment]
.
