### ISSUE TITLE
Merge-AllSysmonXml : Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by Hilmand** [olafhartong/sysmon-modular#35]
What may be the reason ?

**COMPLETE ERROR MESSAGE**
Merge-AllSysmonXml : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:26
+ Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]**.xml') -AsString | O ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Merge-AllSysmonXml], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Merge-AllSysmonXml

**Comment by koppensb** [comment]
Maybe you have seen it already but you forgot a bachslash.
Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml
