### ISSUE TITLE
Question - Difference between compiling the config and the sysmonconfig.xml file included

### ISSUE THREAD

**Issue by AKPoppas** [olafhartong/sysmon-modular#39]
Title says it all, I don't see any reference to the sysmonconfig.xml file that is already included when you git clone the repository. Clearly creates a different ruleset that what you get when you combine all the modular configs as instructed in your readme. If you can explain the difference, I would appreciate it.

**Comment by olafhartong** [comment]
This is the same as all separate modules, this is just included for people as a starter file.

The comments are excluded to save space but the rules are the same, its just the output of git clone and then running the merge script. I hope this clarifies it for you.

**Comment by olafhartong** [comment]
This
