### ISSUE TITLE
Why are the rules in include_mimikatz_inmem.xml grouped with an "and"?

### ISSUE THREAD

**Issue by rtkbkish** [olafhartong/sysmon-modular#42]
How does this work? Aren't they mutually exclusive?

**Comment by olafhartong** [comment]
The point to this rule is to have a base detection for the stock mimikatz.
These DLL's by themselves are loaded a ton of times but all of them by the same process is very rare.
Obviously this can be bypassed when attackers remove functionality from the tool but then there are other events that might catch them
