### ISSUE TITLE
Where do I change HashAlgorithms?

### ISSUE THREAD

**Issue by cowbe0x004** [olafhartong/sysmon-modular#43]
I see there are several files where HashAlgorithms is defined and they're all capturing all hashes. If I just want to capture IMPHASH, where should I change it that will work with the merge? I tried changing it in Merge-SysmonXml.ps1 but that didn't work. Thank you in advance.

**Comment by olafhartong** [comment]
this was overwritten since there were some still in the modules, I believe it should be working now by changing it in the ps1
