### ISSUE TITLE
Encoding on sysmonconfig.xml

### ISSUE THREAD

**Issue by cowbe0x004** [olafhartong/sysmon-modular#52]
Looks like the encoding on sysmonconfig.xml has changed to UCS-2 LE BOM, generated by Azure Pipeline. UCS-2 LE BOM is also the default if you execute Merge-SysmonXml.ps1 with powershell version 5.1. The file size is double of UTF-8. Not sure of the implication, but may be something worth look into?

**Comment by olafhartong** [comment]
Oh, nice. thanks for spotting this. Even though it isn't a problem for Sysmon to load it, opening it in some editors will cause some issues for people. I will fix this right away.

**Comment by olafhartong** [comment]
there, it's UTF-8 now, appreciate the fast spotting

**Comment by cowbe0x004** [comment]
Could you change the encoding from utf8 to utf8NoBOM? BOM is apparently useless for utf8.
