### ISSUE TITLE
sysmonconfig.xml install/update error

### ISSUE THREAD

**Issue by shnlnryn** [olafhartong/sysmon-modular#53]
I am getting an error with the latest update sysmonconfig.xml  (https://github.com/olafhartong/sysmon-modular/blob/master/sysmonconfig.xml) when updating or installing new.

**Error: Incorrect XML configuration: .\sysmonconfig.xml
At line 5, column 11: DTD is prohibited.**

**Comment by olafhartong** [comment]
Interesting, the sysmon in my CI/CD pipeline swallowes it. Just noticed it was also bumped to v11.11

What sysmon version are you using and on which OS?

**Comment by olafhartong** [comment]
I've just validated the config on 2 machines (win10 and server2019) with Sysmon 11.10 and on both it works fine

**Comment by berny275** [comment]
C:\temp> .\sysmon.exe -i .\sysmonconfig.xml -n -accepteula


System Monitor v11.11 - System activity monitor
Copyright (C) 2014-2020 Mark Russinovich and Thomas Garnier
Sysinternals - www.sysinternals.com

Error: Incorrect XML configuration: .\EUT-syscmonconfig.xml
At line 26, column 116: An invalid character was found in text content.

**Comment by shnlnryn** [comment]
> Interesting, the sysmon in my CI/CD pipeline swallowes it. Just noticed it was also bumped to v11.11
> 
> What sysmon version are you using and on which OS?

After updating Sysmon to 11.11 fixed the issue. Thanks @olafhartong

**Comment by shnlnryn** [comment]
> C:\temp> .\sysmon.exe -i .\sysmonconfig.xml -n -accepteula
> 
> System Monitor v11.11 - System activity monitor
> Copyright (C) 2014-2020 Mark Russinovich and Thomas Garnier
> Sysinternals - [www.sysinternals.com](http://www.sysinternals.com)
> 
> Error: Incorrect XML configuration: .\sysmonconfig.xml
> At line 26, column 116: An invalid character was found in text content.
> 
> This looks like it could be an issue with 11.11, but as I don't have 11.10, I can't confirm that.
> I also can't import previous configs that have been posted on here.

@berny275 I came across a similar error if I copied the xml file directly from github. Use git clone or download as zipped file and it should work fine.
