### ISSUE TITLE
Generating a config file

### ISSUE THREAD

**Issue by Yuvraj-Takey** [olafhartong/sysmon-modular#55]
I am using windows 10 pro-OS. while generating a config file using below command(using PowerShell)  I am not getting any error but after completing the process, sysmonconfig.xml is able to generate with an empty file

`
$>. .\Merge-SysmonXml.ps1 `
`
$> Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml
`

**Comment by tongsens** [comment]
I meet this problem too

**Comment by axi0m** [comment]
I'd try to do this command first, assuming you're in the sysmon-modular folder (after cloning the repository or copying the .zip and extracting locally). 

`Import-Module Merge-SysmonXml.ps`

Then do the command

`Merge-AllSysmonXml -Path ( Get-ChildItem '[0-9]*\*.xml') -AsString | Out-File sysmonconfig.xml`

**Comment by newaynewlife** [comment]
There's an error when I excute 
`Import-Module Merge-SysmonXml.ps1`
This is work: 
`Import-Module .\Merge-SysmonXml.ps1`
