### ISSUE TITLE
incorrect SecurityProviders registry path

### ISSUE THREAD

**Issue by lslng** [olafhartong/sysmon-modular#65]
In file 12_13_14_registry_event/include_windows_credential_providers.xml

`<TargetObject name="technique_id=T1003,technique_name=Credential Dumping" condition="begin with">HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SecurityProviders</TargetObject>`

Shoud be:
`<TargetObject name="technique_id=T1003,technique_name=Credential Dumping" condition="begin with">HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\</TargetObject>`

Same error was reported to SwiftOnSecurity but not fixed
https://github.com/SwiftOnSecurity/sysmon-config/issues?q=securityproviders

**Comment by olafhartong** [comment]
Thanks a lot for flagging this, I've addressed it
