### ISSUE TITLE
Is the comparison in exclude_microsoft_drivers.xml secure enough?

### ISSUE THREAD

**Issue by foxmsft** [olafhartong/sysmon-modular#66]
Hey Olaf,

thanks a lot for your work. I was debugging some Sysmon stuff you've been reporting and I'm wondering whether rules such as

```xml
      <RuleGroup groupRelation="or">
        <DriverLoad onmatch="exclude">
          <Signature condition="begin with">Intel </Signature>
          <Signature condition="contains">microsoft</Signature>
          <Signature condition="contains">windows</Signature>
        </DriverLoad>
      </RuleGroup>
```

might be risky. I guess it would be possible, for example, to get a code signing certificate for a legit entity called something like "WindowSwift" - or "windowswift". Signing authorities might raise questions if I use words such as "Intel" (Intel`space` in the rules) and certainly they would complain about "Microsoft", but "windowswift" seems unrelated enough to be granted.

What do you think?

**Comment by olafhartong** [comment]
Totally agree, now with the sub rules it is possible to have them also be signed but forgot they were like this :)
fixing them now to > 

```
                <!--Exclude Microsoft drivers with valid signature-->
                <Rule groupRelation="and">
                    <Signature condition="contains">Microsoft</Signature>
                    <SignatureStatus condition="is">Valid</SignatureStatus>
                </Rule>
```
