### ISSUE TITLE
BSOD on windows 10 machines.

### ISSUE THREAD

**Issue by ravenousld3341** [olafhartong/sysmon-modular#69]
We've had something unusual crop up. From the report I've received.

> Users using a flash drive will cut and paste a file off of their drive and get the attached error. <TargetFilename condition="end with">.sys</TargetFilename>"

I've tried excluding the specific file that was causing the error, error continues. I've also completely removed <TargetFilename condition="end with">.sys</TargetFilename>" from event ID 11, and the issue is still present.

I've reverted back to an old config file from before I implemented modular sysmon, the issue no longer was preset. I am doing more testing on my end to pin this down.

If you find something let me know, if I beat you to it I'll let you know.

The BSOD seems to stem from fastfat.sys, but only happens when using modular sysmon config.

**Comment by olafhartong** [comment]
Did you ever find out more about this ?

**Comment by olafhartong** [comment]
I have not heard anything like it before to be honest

**Comment by ravenousld3341** [comment]
Apologies I didn't get back sooner.

The issue was related to Sysmon 11, Sysmon 13 corrected the problem.
