### ISSUE TITLE
AppInit_DLLs Detection Issue

### ISSUE THREAD

**Issue by innijjer** [olafhartong/sysmon-modular#7]
The following rules don't detect activity unless we take the backslash at the end out since it is a registry value.

`<TargetObject condition="begin with">HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows\Appinit_Dlls\</TargetObject>`
`<TargetObject condition="begin with">HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\Appinit_Dlls\</TargetObject>`

**Comment by olafhartong** [comment]
great find! thank you, I'll go through all modules to make sure these are being removed
