### ISSUE TITLE
^ Symbol in 1_process_creation/include_dosfuscation.xml is UNICODE not ASCII

### ISSUE THREAD

**Issue by kesheldr** [olafhartong/sysmon-modular#71]
Hello

I've just noticed that the ^ (hat) symbol in https://github.com/olafhartong/sysmon-modular/blob/master/1_process_creation/include_dosfuscation.xml is actually a UNICODE character  and not the ASCII version.

The ASCII version acts as a concatenation operator in CMD.EXE but the UNICODE version does not appear to (at least on Windows 10).  I think you probably intended to use the ASCII variant.

Thanks

Kev

**Comment by olafhartong** [comment]
well spotted, thank you!
Not sure how that got to be, fixed it

**Comment by kesheldr** [comment]
No worries. Glad we can help.

Kev

--
Kevin Sheldrake
Microsoft Threat Intelligence Centre
