### ISSUE TITLE
latest config erroring out

### ISSUE THREAD

**Issue by spitzd** [olafhartong/sysmon-modular#78]
Error: Incorrect XML configuration: .\sysmonconfig.xml
Reason: Element 'ProcessTampering' is unexpected according to content model of parent element 'RuleGroup'.
Expecting: ProcessCreate, FileCreateTime, NetworkConnect, ProcessTerminate, DriverLoad, ImageLoad, CreateRemoteThread, RawAccessRead, ProcessAccess, FileCreate, RegistryEvent, FileCreateStreamHash, PipeEvent, WmiEvent, DnsQuery, FileDelete, ClipboardChange.

**Comment by olafhartong** [comment]
Are you sure? In my pipeline it all works great
Did you generate it yourself?

**Comment by spitzd** [comment]
Hey Olaf, my apologies. Yes, it was a mistake I made. Closing the non-issue :-)
