### ISSUE TITLE
Question - Generate config with PSSysmonTools

### ISSUE THREAD

**Issue by markus-nclose** [olafhartong/sysmon-modular#8]
Hi. 

I'm following your instructions, but PSSysmonTools doesn't allow scheme 4.1. How do you generate config?

**Comment by olafhartong** [comment]
Hi Markus,

Thanks for checking in. I found that out as well yesterday evening. I’m already working on an update for PSSysmon to support 4.1. 
I’ll post an update here when I’ve pushed it.

**Comment by markus-nclose** [comment]
Awesome! Looking forward to testing out the new version.

**Comment by olafhartong** [comment]
I've fixed PSSysmonTools, you can find my version here till the pull request is accepted;
https://github.com/olafhartong/PSSysmonTools

Addionally the generated sysmonconfig.xml of all modules is also in the root of the repository
