### ISSUE TITLE
Event ID 15: FileCreateStreamHash - Redundant entries

### ISSUE THREAD

**Issue by Yuvraj-Takey** [olafhartong/sysmon-modular#87]
I was looking Event ID 15 in sysmonconfig.xml file. While I found that there are 3 exact similar entries of 
`"<TargetFilename condition="contains">Downloads</TargetFilename>"`. 
Those redundant entries are needed in XML, if it is, what is it used for?

**Comment by olafhartong** [comment]
They are not, thank you for pointing them out. they have become obsolete and I have addressed this.
