### ISSUE TITLE
typo in file name 'include_living_of_the_land.xml'

### ISSUE THREAD

**Issue by alireza-ebrahimi** [olafhartong/sysmon-modular#89]
right now there are 2 files in process creation directory with names:
- include_living_off_the_land.xml 
- include_living_of_the_land.xml 

with almost identical content.
I think maybe one of these files is redundant and should be deleted. I also checked that contents of both files exist in sysmonconfig.xml then maybe this causes some inconsistencies in sysmon log generation

**Comment by olafhartong** [comment]
thanks for spotting this, my bad. I merged a PR and never spotted this duplicate file. correcting this in next push
