### ISSUE TITLE
The '1_process_creation/include_living_of_the_land.xml' rule item has a duplicate

### ISSUE THREAD

**Issue by MyKings** [olafhartong/sysmon-modular#9]
**tasklist.exe**

Line 11: https://github.com/olafhartong/sysmon-modular/blob/master/1_process_creation/include_living_of_the_land.xml#L11

Line 58: https://github.com/olafhartong/sysmon-modular/blob/master/1_process_creation/include_living_of_the_land.xml#L58

**qprocess.exe**

Line 14: https://github.com/olafhartong/sysmon-modular/blob/master/1_process_creation/include_living_of_the_land.xml#L14

Line 53: https://github.com/olafhartong/sysmon-modular/blob/master/1_process_creation/include_living_of_the_land.xml#L53

Is there an item for `ParentImage`?

**Comment by olafhartong** [comment]
Thanks for spotting them! Removed the duplicate lines
