### ISSUE TITLE
Thousands of "network connect" logs on single RDP (port 3389) connection

### ISSUE THREAD

**Issue by Suirand1** [olafhartong/sysmon-modular#90]
Using Sysmon 13.01 In some win10x64 PCs I am facing tons of network connect logs when single RDP connection is established and used for a while. Any ideas how to deal with it? Are you facing the same?

**Comment by Suirand1** [comment]
OK I managed to find the solution myself. It was a surprise for me to figure out that  Microsoft RDP can use UDP protocol as transport for RDP. Each UDP packet is like a new connection for Sysmon.  I would suggest to update config not to log UDP packets for 3389 port since it is very noisy.

**Comment by olafhartong** [comment]
Oh nice, RDP can indeed work also over UDP in some cases. I'll add that exclude to the repo, thanks for reaching out!
