### ISSUE TITLE
Bug GroupRelation

### ISSUE THREAD

**Issue by V1D1AN** [olafhartong/sysmon-modular#92]
Hi @olafhartong

I have a problem with Sysmon v13.10 and your configuration file.

All the rules with the GroupRelation="and" don't work. 
The rules behave as GroupRelation="or"

This causes a lot of false positives

Thanks :)

**Comment by olafhartong** [comment]
Hi, this has nothing to do with the config itself. 
there are a few parsing bugs in the public version of 13.10. 

I’m working with the sysinternals team to get them resolved

**Comment by portland80** [comment]
> Hi @olafhartong
> 
> I have a problem with Sysmon v13.10 and your configuration file.
> 
> All the rules with the GroupRelation="and" don't work.
> The rules behave as GroupRelation="or"
> 
> This causes a lot of false positives
> 
> Thanks :)

Thanks for the posting. We already had this finding last week. Especially the "include_windows_integrity_monitoring.xml" generates a lot of noise. Thanks @olafhartong for reporting to the sysinternals team and your great work with sysmon-modular.

**Comment by olafhartong** [comment]
should be fixed in 13.22 afaik
