### ISSUE TITLE
Source file name in XML

### ISSUE THREAD

**Issue by istvanSA** [olafhartong/sysmon-modular#94]
Maybe its an nice idea to have the filename added to "the name = " for echt event

so for example 

name="technique_id=T1021.002,technique_name=SMB/Windows Admin Shares"

turns into 

name="technique_id=T1021.002,technique_name=SMB/Windows Admin Shares,filename=include_metasploit.xml"

then it would be much easier in an siem or other solution to find out what exact rule triggered an event. This can be usefull while implementing this solution and finding out what rules are generating a lot of events etc

**Comment by olafhartong** [comment]
Thanks for reaching out! It's a nice idea. 
However I don't want to make the rule names too long, this makes the lines very long which doesn't help with editing.
It should be relatively fast to search for the rule that triggered it in most cases, which doesn't justify the effort of adding it for me :)
