### ISSUE TITLE
Event 10 version 1320

### ISSUE THREAD

**Issue by bonusland** [olafhartong/sysmon-modular#98]
Hello,

I can see in your config you include AppData in event code 10, but when using something like ms teams which runs from userland(appdata) I am generating around 4k events as below per hour. I am thinking that this can be the same for some other modern user apps that run from user's AppData. Do you any suggestion to tune down the noise?

Process accessed:
RuleName: technique_id=T1036,technique_name=Masquerading
UtcTime: 2021-05-27 11:11:51.365
SourceProcessGUID: {40d49903-775f-60af-c101-00000000e900}
SourceProcessId: 7044
SourceThreadId: 11144
SourceImage: C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe
TargetProcessGUID: {40d49903-69c8-60af-b800-00000000e900}
TargetProcessId: 9192
TargetImage: C:\WINDOWS\Explorer.EXE
GrantedAccess: 0x40
CallTrace: C:\WINDOWS\SYSTEM32\ntdll.dll+9d2e4|C:\WINDOWS\System32\KERNELBASE.dll+2bcee|C:\WINDOWS\System32\shcore.dll+19b4d|C:\WINDOWS\System32\shcore.dll+1b663|C:\WINDOWS\System32\shcore.dll+1b529|C:\WINDOWS\System32\shcore.dll+19aa5|C:\WINDOWS\SYSTEM32\windows.storage.dll+1771a1|C:\WINDOWS\SYSTEM32\windows.storage.dll+dade7|C:\WINDOWS\SYSTEM32\windows.storage.dll+134c77|C:\WINDOWS\SYSTEM32\windows.storage.dll+134ed2|C:\WINDOWS\SYSTEM32\windows.storage.dll+2c262|C:\WINDOWS\SYSTEM32\windows.storage.dll+2bdcb|C:\WINDOWS\SYSTEM32\windows.storage.dll+2bad9|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+3e065c3|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+3e04a44|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+366fb92|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+366fb18|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+e21a8c|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+dddc2f|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+ddd1b1|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+ddce31|C:\Users\Temp\AppData\Local\Microsoft\Teams\current\Teams.exe+165dcd2|UNKNOWN(0000005500000000)

**Comment by hkelley** [comment]
We're seeing enormous noise coming from Teams and Chrome for simple process events too.  

Based on what I know of the current tactics,  I am focusing on ImageLoad events rather that cross-process events.   The DLL hijacking opportunities in Teams and OneDrive will likely be the entry point for an adversary,  and they seem to be less-noisy and more tunable based on DLL signatures.

https://milosilo.com/hacking/microsoft-teams-proxy-dll-hijacking/

**Comment by washuu** [comment]
Hello, 
I allow-listed Teams by using 
`<Rule groupRelation="and">
				<SourceImage condition="end with">\Teams.exe</Image>
				<SourceImage condition="contains">\AppData\Local\Microsoft\Teams\</TargetFilename>
</Rule>`
I know it's kind of crude. But so MS Teams is. :-)
