### ISSUE TITLE
overlaping rule causing alot of 12/13 events

### ISSUE THREAD

**Issue by PurpleV0id** [olafhartong/sysmon-modular#99]
Both of these rules overlap and were causing alot of ec 12/13 events for events containing \Microsoft\Office\
We removed include_office_oulook.xml and we stopped receiving them
12_13_14_registry_event/include_office_oulook.xml
12_13_14_registry_event/include_office_oulook_addins.xml

**Comment by olafhartong** [comment]
Thanks for letting me know, I'll look into improving this
